column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
quote_style = 'AutoPreferSingle'
indent_width = 2
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
